### ISSUE TITLE
Weird warping compatibility issue with Better Status Indicators.

### ISSUE THREAD

**Issue by andylmfao** [Slddev/ModernX-Theme#10]
![image](https://user-images.githubusercontent.com/63781863/147793174-300ab61a-942a-4556-87f1-b623a90947ed.png)
![image](https://user-images.githubusercontent.com/63781863/147793176-fc3b9750-c46b-40aa-a319-b196f30ded6a.png)

**Comment by andylmfao** [comment]
In this case It's the warped red ring indicating DND that's the actual users' status.

**Comment by andylmfao** [comment]
Update: This seems to be an issue with the "Round avatars" module that you can enable.

**Comment by Slddev** [comment]
Yes, round avatars afaik doesn't support Round Avatars. Just disable that and everything should be fine.

**Comment by andylmfao** [comment]
Okay thats fair, is there a way to disable the entire round avatar part of the theme so i can use only better status indicators

**Comment by Lock-The-Door** [comment]
> Okay thats fair, is there a way to disable the entire round avatar part of the theme so i can use only better status indicators

Go to modernx-discord.theme.css and comment out:
`@import url("https://discordstyles.github.io/RadialStatus/dist/RadialStatus.css");`
