### ISSUE TITLE
Channel notices are invisible/hidden.

### ISSUE THREAD

**Issue by spectrapulse** [Slddev/ModernX-Theme#11]
Channel notices such as the identity notice are hidden. This can lead to confusion why one can't send messages in channels.
![image](https://user-images.githubusercontent.com/20131658/147823933-27801b18-78c3-4c63-bd94-9bfdcc6e402f.png)
![image](https://user-images.githubusercontent.com/20131658/147823955-96c31291-4476-49ae-a4a0-a951ee6e9217.png)

**Comment by Slddev** [comment]
This is intentional. Although I will setup some notice about the phone badge and etc.
