### ISSUE TITLE
Username alignment weirdness

### ISSUE THREAD

**Issue by TranquillyUnpleasant** [Slddev/ModernX-Theme#13]
For longer usernames, the username can go out of the box that contains it, which looks a bit weird, maybe have it fit content?

![image](https://user-images.githubusercontent.com/62061444/148986725-e7e40bc3-0706-4a4e-93e7-6bb1c39c90f5.png)

**Comment by Slddev** [comment]
Will make it overflow, I haven't thought of this.

**Comment by Slddev** [comment]
Fixed in [`a43785b`](https://github.com/Slddev/ModernX-Theme/commit/a43785b9d0afd8473da346ad3abba2d1c4d9f07b#diff-72c10e096c4deb8cb05fd686697f1be3a7ca37da64aabca9b7224d0bb16ef4ed)
