### ISSUE TITLE
Channel topics overlapping with member list.

### ISSUE THREAD

**Issue by Spencer-0003** [Slddev/ModernX-Theme#15]
Channels with really long topics overlap with the member list.
![image](https://user-images.githubusercontent.com/36741900/149649961-b4880253-0950-4e2d-a82b-3bc89670b6e7.png)

**Comment by Slddev** [comment]
Weird, cannot reproduce...
![image](https://user-images.githubusercontent.com/74999267/149699908-980e08ae-5456-41f5-8879-3f10972e7d53.png)

**Comment by Slddev** [comment]
Maybe you have some custom CSS that may affect the channel info's width? Or maybe a plugin?

**Comment by Spencer-0003** [comment]
I've got no custom CSS and it still happens with all plugins disabled.

**Comment by Slddev** [comment]
May I know what resolution and zoom level your Discord is running at?

**Comment by Spencer-0003** [comment]
Running full screen on my desktop (1920x1080) and my zoom level is 100.

**Comment by Slddev** [comment]
I really can't reproduce this, I tested it on a 1080p monitor and the overflow works.

**Comment by Spencer-0003** [comment]
Issue seems to be fixed after a Discord update(?) Will close the issue now.
