### ISSUE TITLE
[BUG] The scroll fade in the channel list doesn't disappear

### ISSUE THREAD

**Issue by Lock-The-Door** [Slddev/ModernX-Theme#16]
### Client Mod

Powercord

### Description of bug

In a server with lots of channels, there is a fade at the bottom of the channel list, causing the last channel to be dimmer than the rest and also making it harder to see

### Steps to reproduce

Go into a server with enough channels that it causes an overflow
Scroll to the bottom

### Screenshots

![image](https://user-images.githubusercontent.com/49077851/151487772-25889447-54a6-4ad9-9671-58945206a80d.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
This is an intended feature. This does not affect interaction with a channel or voice channel. This will not be changed.
