### ISSUE TITLE
[BUG] Tooltips go off screen

### ISSUE THREAD

**Issue by Lock-The-Door** [Slddev/ModernX-Theme#17]
### Client Mod

Powercord

### Description of bug

When the member list is hidden, tooltips such as the one on the gift button or the slowmode icon get cut offscreen

### Steps to reproduce

Hide the member list 
Hover over the discord gift button or a slow mode icon in a slow mode channel

### Screenshots

![image](https://user-images.githubusercontent.com/49077851/151678888-b53e970b-b4d5-47af-b738-e42608a980bf.png)
![image](https://user-images.githubusercontent.com/49077851/151678893-11534754-2ee9-4f9c-9776-94174c7383a9.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Lock-The-Door** [comment]
Just as an added note, it seems that the slowmode tooltip only goes offscreen when you are not bypassing it

**Comment by Slddev** [comment]
Fixed in [`8e58cd5`](https://github.com/Slddev/ModernX-Theme/commit/8e58cd5682edc6373193f3a2a611fbb479f86046)
