### ISSUE TITLE
[Feature] question about horizontal server list

### ISSUE THREAD

**Issue by JackeLeMort** [Slddev/ModernX-Theme#18]
### Suggestion

is it possible to ta bake the server list to the original spot ?

### Benefit

just didn't wanted to make this as a bug

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hey ! 
Just a little question, is it possible to just get the server list back to its original position ? because i use discord on a screen in portrait mode, so i don't see a lot of my server's icon at at time, i tried to search a little in the code but i don't have enough knowledge to find what i search, so i'm just asking 🤷, 
don't feel obligate i can do without and have a nice day

**Comment by Slddev** [comment]
Currently you cannot. This maybe added later but right now it's not gonna be added.
