### ISSUE TITLE
Channel header bug (Other languages)

### ISSUE THREAD

**Issue by alije123** [Slddev/ModernX-Theme#2]
![image](https://user-images.githubusercontent.com/33022255/146293990-6a4694a4-123e-4e9d-a327-8ef27a1cd8ae.png)
Thank you for beautiful theme, but when i installed it i seen this.
upd. and this 
![image](https://user-images.githubusercontent.com/33022255/146294843-e06f4684-378a-4707-8119-683094181db4.png)

**Comment by alije123** [comment]
I checked the problem appears if the language is not English

**Comment by Slddev** [comment]
Other languages are currently not supported. Although you can help add support to your language if you have the proper knowledge to code CSS. If you do so, please drop a PR.

**Comment by 9Datenshi** [comment]
So, I was trying to solve because I have the same bug, but in other lang, for myself I found this solution:

`.container-2wlB3z {
	height:calc(100% + var(--app-info-bar-height));
    margin-top: 100px;
}`

I just have 1 or 2 months studying CSS, sorry if it doesn't help.
