### ISSUE TITLE
[Feature] Add option to disable blur

### ISSUE THREAD

**Issue by aragubas** [Slddev/ModernX-Theme#22]
### Suggestion

I want an option to disable blur on the top bar

### Benefit

Because CSS blur lags the hell out of discord, and makes the apps feel slow and unresponsive

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Accessibility feature for users with an iGPU, discord itself already runs just a little bit slow but with this blur it becomes unresponsive.

**Comment by GreenMan36** [comment]
Bump

**Comment by Slddev** [comment]
Alexis has started work on V2 of the original theme. This will get archived soon after. Will not be adding this feature.
