### ISSUE TITLE
[Feature] Voice Connected / VC Timer UI Improvement

### ISSUE THREAD

**Issue by FnigePython** [Slddev/ModernX-Theme#24]
### Suggestion

Voice Connected area should be a proper button rather than an annoying and also invisible area (guessing its hidden behind the voice shenanigans)

### Benefit

Generally would make stuff like seeing what voice server you are in much easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/35159947/156885431-17fb9bd2-8ebe-4d43-b4d3-25363b52711c.png)
This should instead not require hovering or it should be in a way more accessible place. (Like to the right of that deafen)

The icon for accessing this should honestly be something like the missing controls icon on the spotify modal

**Comment by Slddev** [comment]
This is how the original maker intended it to be, and it will stay the same.
