### ISSUE TITLE
[BUG] Server list disappears

### ISSUE THREAD

**Issue by JoeskieeMedia** [Slddev/ModernX-Theme#27]
### Client Mod

PowerCord

### Description of bug

Whenever I paste something longer than 4 lines in the box where you type out your message, the horizontal server list disappears. If you need any more info related to it, just let me know

### Steps to reproduce

Paste anything more than 4 lines in the message box

### Screenshots

https://i.imgur.com/5D2G5RN.png

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by JoeskieeMedia** [comment]
I'll keep looking over it to see if I can help with a fix.

**Comment by Slddev** [comment]
ModernX has declared EOD. For more information go [here](https://github.com/Slddev/ModernX-Theme/blob/master/EOD.md).
