### ISSUE TITLE
[BUG] Need some fix in the lower part of the windows

### ISSUE THREAD

**Issue by marioporfirio** [Slddev/ModernX-Theme#29]
### Description of bug

Need to add some gap in the lower part of the window, there is a transparent gradient that difficult to see the voice chats and the participants.

### Steps to reproduce

Just scroll down channel list to the bottom.

### Screenshots

![image](https://user-images.githubusercontent.com/21208925/180359434-2301181a-38bb-4846-b547-a42a0969d60c.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
This is an intended part of the theme.
