### ISSUE TITLE
[Betterdiscord] Submit the theme to the official website

### ISSUE THREAD

**Issue by isaktexas** [Slddev/ModernX-Theme#30]
### Suggestion

Title^

### Benefit

Easier access

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Slddev** [comment]
Please read the README. You will see why this theme is not uploaded there.

**Comment by isaktexas** [comment]
might I ask if it's the ¨Original Work¨ requirement that's the problem?
