### ISSUE TITLE
[BUG] Embeds broken/unreadable

### ISSUE THREAD

**Issue by Spencer-0003** [Slddev/ModernX-Theme#31]
### Client Mod

Powercord

### Description of bug

Half of the embed is grey.

### Steps to reproduce

View an embed

### Suspected cause

Discord update

### Screenshots

![image](https://user-images.githubusercontent.com/36741900/182366597-770890a5-881d-4463-ae03-57a8c20767f0.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sowd0404** [comment]
![image](https://user-images.githubusercontent.com/70187756/182366700-b3249ddf-eccf-427b-998b-7d438f8a4e4d.png)
lmao

**Comment by Slddev** [comment]
Fixed in [`727fef9`](https://github.com/Slddev/ModernX-Theme/commit/727fef9f0cbe24206ba18ac4b0b5b1555f1740b6).
