### ISSUE TITLE
[Feature] Original colors

### ISSUE THREAD

**Issue by Minnona** [Slddev/ModernX-Theme#32]
### Suggestion

Hey, I like the layout of this theme very much, but the colors are a little bit too dark for my taste. Is is possible to restore original color palette?

### Benefit

I think Discord team has really nailed down the color palette and it looks comfortable and contrast enough across all devices and screens.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Slddev** [comment]
This will not be implemented in the theme, sorry.
