### ISSUE TITLE
[BUG] Issues with scrolling the server list

### ISSUE THREAD

**Issue by Toricane** [Slddev/ModernX-Theme#33]
### Client Mod

Powercord

### Description of bug

When scrolling in the server list, it only scrolls when the cursor is over a server or folder.
It should be able to scroll while my cursor is on the top bar, not only precisely on a server.
For example, when the cursor is in between two servers, it won't scroll.

Another issue is that there is no support for side-scrolling.
When I use a touchpad, it would be convenient for the list to scroll when I move two fingers to the left or right.
Having to use vertical scrolling for a horizontal bar always confuses me.

Please fix the above issues, thanks.

### Steps to reproduce

Issue 1:
* Put your cursor on the horizontal server list, but not directly on top of a server or folder
  * For example, in between two servers, above the servers, or below them
* Try to scroll

Issue 2:
* Attempt to scroll horizontally (on a touchpad)
  * One way is to put two fingers on the touchpad at the same time and move it left to right and vice versa
  * To vertical scroll, you instead move them up or down

### Screenshots

![DiscordCanary_P38GeLTkDJ](https://user-images.githubusercontent.com/73972068/187004544-65c5f56e-f702-428d-a00a-c4a6d3205533.gif)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
There is no way to implement the side-scrolling feature you said without using a plugin. And the scrolling on the top-bar I think was intentional as the original theme had the same system of have the cursor on the icon.
