### ISSUE TITLE
[BUG] Discord Call buttons get misaligned when streaming or using Spotify control plugin

### ISSUE THREAD

**Issue by Xutine** [Slddev/ModernX-Theme#34]
### Client Mod

Powercord

### Description of bug

The background bar doesn't increase in width when streaming which causes the deafen button to not be in the bar and when using Spotify Control the visual bugs get worse

### Steps to reproduce

just start streaming with or without Spotify control plugin found here https://github.com/mwittrien/BetterDiscordAddons

### Suspected cause

code doesn't extend the bar and can't handle the extra height from Spotify control

### Screenshots

![image](https://user-images.githubusercontent.com/50846954/188336979-c2b38d74-4f33-4605-8390-6d877479c6a2.png)
![image](https://user-images.githubusercontent.com/50846954/188336987-abe0de6b-646c-4aa7-8a86-7e3f4e618371.png)
![image](https://user-images.githubusercontent.com/50846954/188337012-fb0abf31-c6d2-4a73-8e18-f661bf4153f4.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
Since you are using Powercord, please use the built-in `powercord-spotify` plugin. As for the background of the call buttons, this bug is hard to fix as they become too big when you aren't on a game.
