### ISSUE TITLE
[BUG] Theme doesn't working

### ISSUE THREAD

**Issue by sSwaf** [Slddev/ModernX-Theme#35]
### Client Mod

BetterDiscord

### Description of bug

When I'm choose a ModernX Theme how basic theme in my Discord - theme don't working. I see, that a couple of files don't working link. Please, fix it problem.

### Steps to reproduce

Loading a files on new hosting.

### Suspected cause

Don't working link

### Screenshots

https://imgur.com/a/nk5joHz

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
Please check this release: [22.9.24b](https://github.com/Slddev/ModernX-Theme/releases/tag/22.9.24b)
