### ISSUE TITLE
Profile error

### ISSUE THREAD

**Issue by N1zard** [Slddev/ModernX-Theme#37]
### Description of bug

The background in the user profile does not work correctly

### Steps to reproduce

Click on any user profile

### Screenshots

![98](https://user-images.githubusercontent.com/114083567/200180458-c277f0ff-22f3-4566-8a8f-49ec681d8673.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
ModernX has declared EOD. For more information go [here](https://github.com/Slddev/ModernX-Theme/blob/master/EOD.md).
