### ISSUE TITLE
[BUG] Chat doesn't load

### ISSUE THREAD

**Issue by j3TO** [Slddev/ModernX-Theme#38]
### Client Mod

BetterDiscord

### Description of bug

When you open any of the chats, regardless of personal chat or general chat just do not load

### Steps to reproduce

I tried reinstalling the plugin, discord, betterdiscrod, but nothing changes

### Screenshots

![image](https://user-images.githubusercontent.com/78072141/200621847-10539b6c-fa31-48e1-8be5-b53538ded532.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Slddev** [comment]
ModernX has declared EOD. For more information go [here](https://github.com/Slddev/ModernX-Theme/blob/master/EOD.md).
