### ISSUE TITLE
Fix for Spotify plugin

### ISSUE THREAD

**Issue by M4kaze** [Slddev/ModernX-Theme#4]
Since the Spotify plugin is build in into Powercord, a fix for it would be great!

Currently it looks kinda broke.

This is in the bottom left of Discord.
![image](https://user-images.githubusercontent.com/31509082/146692186-302d4738-6d41-4464-89f6-dc2e3c45aff1.png)

And the Icon of the song is up there, where the User Stuff ist.
![image](https://user-images.githubusercontent.com/31509082/146692202-1d67d920-462f-4c35-ad84-ec469a1470dc.png)

It would be cool if the Spotify control stuff could be left on the bottom left. But like the controls aligned in the center with the Icon of it.

So it wouldn't look as broke as it looks.

**Comment by Slddev** [comment]
Fixing it now.

**Comment by Slddev** [comment]
Fixed

**Comment by M4kaze** [comment]
The Icon of the song is still left of the avatar (second screenshot of first message)

Is it possible to move it to the controls?

**Comment by Slddev** [comment]
> The Icon of the song is still left of the avatar (second screenshot of first message)
> 
> Is it possible to move it to the controls?

I'm trying to move it to the controls but for now I'm planning to just remove it. Maybe in the future I'll move it to the controls successfully.
