### ISSUE TITLE
Channel Description Overflow, User list starts pretty high up

### ISSUE THREAD

**Issue by notKnei** [Slddev/ModernX-Theme#5]
Before anything I am so sorry for bringing these up. With a note I don't know CSS suggestions I am giving are just assumptions

![image](https://user-images.githubusercontent.com/76569087/147322668-fc063327-ee14-48dc-af30-28112da9da5c.png)
1. Channel description overflows onto other parts of the top bar set max width or something 
2. Member list starts pretty high up causing roles that have longer names to be hidden behind the thread, notification, pinned, etc buttons. Fix could be to make them appear below the buttons

![image](https://user-images.githubusercontent.com/76569087/147322860-d7d8a475-d322-4d7e-aba2-6060a7709584.png)
3. Intended? not sure but yeah server banner doesn't load all the way.

![image](https://user-images.githubusercontent.com/76569087/147322943-f30526f0-1512-421e-9344-1b358a904260.png)
4. not sure if this is a theme issue? but yeah that 'new' tag shouldn't be there if the end of server list isn't hidden.

I hope I didn't ruin your day and uh I suppose have a nice Christmas... Yeah this season I am giving the wrong gifts ( Hopefully I don't notice more, sorry I am not able to help, I am horrible with CSS )
Also, may I request to be able to modify some parts to my own liking? ( Such as guild channel list width, friends DM list width, etc? )

**Comment by Slddev** [comment]
Make sure you are using English US as your language. And yes you can modify stuff on the CSS file. 

Check #2 aswell.
