### ISSUE TITLE
Titlebar in DM Group view isn't extended as far as it should be.

### ISSUE THREAD

**Issue by spectrapulse** [Slddev/ModernX-Theme#6]
Currently in the DM Group view the title bar doesn't extend as far as it should. Resulting in the icons of the icon toolbar to float over the members heading.
![DiscordCanary_eTYTLNCxnt](https://user-images.githubusercontent.com/20131658/147376804-2705b609-f5c5-40e1-b14f-b25f2ff4e5c1.png)

**Comment by Slddev** [comment]
Make sure you are using English US. #2

**Comment by spectrapulse** [comment]
> Make sure you are using English US. #2

That issue is not relevant to the bar not being extended as far as it should be. Shouldn't it be consistent with the way that it looks in the guild view? Which is extended all the way to the right border of the window? 
![image](https://user-images.githubusercontent.com/20131658/147379698-3ccd71a6-71fd-4b5c-a98c-f22fb29c53e8.png)

**Comment by Slddev** [comment]
That isn't how its supposed to look like. The channel info + buttons are supposed to only extend before the member list. 

Guild:
![image](https://user-images.githubusercontent.com/74999267/147413480-1d87cc37-7f56-41cd-a5de-83f348143c99.png)
Group DM:
![image](https://user-images.githubusercontent.com/74999267/147413439-573ac4c2-18e7-4474-ba15-e5794b0100c5.png)
