### ISSUE TITLE
Member sidebar isn't themed in Group DM view

### ISSUE THREAD

**Issue by spectrapulse** [Slddev/ModernX-Theme#7]
Self explanatory.
![image](https://user-images.githubusercontent.com/20131658/147376837-e6737f62-c906-433d-a2dd-146a888ffc0e.png)

**Comment by Slddev** [comment]
Will fix in 2022.

**Comment by Slddev** [comment]
After further investigation, this is intentional to indicate something about the user in the Group DM? I'm not sure but thats what I noticed.
