### ISSUE TITLE
Member-wrapper element is larger than it's parent.

### ISSUE THREAD

**Issue by spectrapulse** [Slddev/ModernX-Theme#8]
Because of the wrapper element being larger than the container than it's in. Statuses and names get cut by the border of the window and being able to horizontally scroll in the container.
![pQmpfOPNYc](https://user-images.githubusercontent.com/20131658/147376897-b2722646-4603-4045-bc5c-df99363447ea.gif)

**Comment by Slddev** [comment]
Will fix in 2022.

**Comment by Slddev** [comment]
Quick question: How are you suppose to recreate this? I can't seem to scroll horizontally.

**Comment by spectrapulse** [comment]
I'm not entirely sure to be completely honest. I have a mousewheel that can scroll horizontally... I noticed it by the statuses cutting off and tried horizontal scrolling and that was the result. If you don't have the ability to do so I'm not sure what to tell you.

**Comment by Slddev** [comment]
huh. Anyways I'll try to prevent this by making the wrapper smaller. Also what mouse do you have?

**Comment by spectrapulse** [comment]
I have a G903 from Logitech

**Comment by Slddev** [comment]
Investigating further, they seem to have the same width. I'm not sure how you are able to do that, since its supposed to be impossible.
