### ISSUE TITLE
Settings Icon dropdown flickering. 

### ISSUE THREAD

**Issue by andylmfao** [Slddev/ModernX-Theme#9]
https://user-images.githubusercontent.com/63781863/147792960-0862de20-4a23-4e56-a363-ac1f400b7e9b.mp4

**Comment by andylmfao** [comment]
Update: Seems to be a compatibility issue with the the "Pop!"

**Comment by Slddev** [comment]
Pop! will not be supported. Please disable the module and everything should be fine.
